=== irisrm1997/LENGUAJES-DE-MARCAS/alumnos_ns.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://lmsgi.ud04.iessanclemente.net"
xmlns:tn="http://lmsgi.ud04.iessanclemente.net"
elementFormDefault="qualified">
    <!-- elemento raíz -->
    <xs:element name="alumnos" type="tn:datosAlum"/>
    <!-- Definicion del tipo datosAlum -->
    <xs:complexType name="datosAlum">
        <xs:sequence>
            <xs:element name="alumno" type="tn:datos" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definicion del tipo datos -->
    <xs:complexType name="datos">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" minOccurs="1"  maxOccurs="1"/>
            <xs:element name="apellidos" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="direccion" type="tn:datosDireccion" minOccurs="1" maxOccurs="1"/>
            <xs:element name="contactar" type="tn:datosContactar" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <!-- Atributos  del elemento usuario -->
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="datosDireccion">
        <xs:sequence>
            <xs:element name="domicilio" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="codigo_postal" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                        <xs:attribute name="cp" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="localidad" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="provincia" type="xs:string" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
    </xs:complexType>
    <xs:complexType name="datosContactar">
        <xs:sequence>
            <xs:element name="telf_casa" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="telf_movil" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="telf_trabajo" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="email" minOccurs="0" maxOccurs="unbounded" >
                <xs:complexType>
                    <xs:attribute name="href" type="xs:string"/>
                </xs:complexType>
            </xs:element>
           </xs:sequence>
    </xs:complexType>
</xs:schema>

=== irisrm1997/LENGUAJES-DE-MARCAS/alumnos_ns_prefijo.xml
<?xml version="1.0" encoding="utf-8"?>
<al:alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xmlns:al="http://lmsgi.ud04.iessanclemente.net"
xsi:schemaLocation="http://lmsgi.ud04.iessanclemente.net alumnos_ns.xsd">
    <al:alumno>
        <al:nombre>Jose Ramón</al:nombre>
        <al:apellidos>García González</al:apellidos>
        <al:direccion>
            <al:domicilio>El Pez, 12</al:domicilio>
            <al:codigo_postal cp="85620"/>
            <al:localidad>Suances</al:localidad>
            <al:provincia>Cantabria</al:provincia>
        </al:direccion>
        <al:contactar>
            <al:telf_casa>985623165</al:telf_casa>
            <al:telf_movil>611233544</al:telf_movil>
            <al:telf_trabajo>965847536</al:telf_trabajo>
            <al:email href="pepito@educadistancia.com"/>
        </al:contactar>
    </al:alumno>
    <al:alumno>
        <al:nombre>Carlos</al:nombre>
        <al:apellidos>López Pérez</al:apellidos>
        <al:direccion>
            <al:domicilio>El Cangrejo, 25</al:domicilio>
            <al:codigo_postal cp="86290"/>
            <al:localidad>Santillana</al:localidad>
            <al:provincia>Cantabria</al:provincia>
        </al:direccion>
        <al:contactar>
            <al:telf_casa>931132565</al:telf_casa>
            <al:telf_movil>623863544</al:telf_movil>
            <al:telf_trabajo>984657536</al:telf_trabajo>
            <al:email href="carlos@educadistancia.com"/>
        </al:contactar>
    </al:alumno>
</al:alumnos>
